// packages/react-app/src/layout/index.tsx
import { useLocation, Outlet } from 'react-router-dom';
// import { qiankunWindow } from '@/plugins/qiankun/helper';
// import { menusList } from '@/config';
import RootPage from '@/pages/rootPage';
import styles from './layout.module.scss';

const Layout = () => {
  const location = useLocation();
  const isRootPage = location.pathname === '/';

  return (
    <div className={styles.layout}>
      {/* {!qiankunWindow.__POWERED_BY_QIANKUN__ && (
        <div className={styles['layout-header']}>
          <Link to="/">React 应用</Link>
        </div>
      )} */}
      {/* <div className={styles['layout-container']}> */}
      {/* qiankunWindow.__POWERED_BY_QIANKUN__ 为 true 时，不显示菜单 */}
      {/* {!qiankunWindow.__POWERED_BY_QIANKUN__ && (
          <div className={styles['layout-left']}>
            {menusList.map((item, index) => (
              <Link key={item?.id || index} to={item.path}>
                {item.name}
              </Link>
            ))}
          </div>
        )} */}
      <div className={styles['layout-right']}>
        {isRootPage && <RootPage />}
        <Outlet />
        {/* </div> */}
      </div>
    </div>
  );
};

export default Layout;

// packages/vue-app/src/layout/index.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useRoute } from 'vue-router';
// import { qiankunWindow } from 'vite-plugin-qiankun/es/helper';
// import { menusList } from '@/configs';
import RootPage from '@/pages/rootPage/index.vue';

const route = useRoute();
const isRootPage = computed(() => route.path === '/');
</script>

<template>
  <div className="layout">
    <!-- <div className="layout-header" v-if="!qiankunWindow.__POWERED_BY_QIANKUN__">
      <router-link :to="'/'"> Vue 应用 </router-link>
    </div> -->
    <div className="layout-container">
      <!-- qiankunWindow.__POWERED_BY_QIANKUN__ 为 true 时，不显示菜单 -->
      <!-- <div className="layout-left" v-if="!qiankunWindow.__POWERED_BY_QIANKUN__">
        <template v-for="item in menusList" :key="item?.id">
          <router-link :to="item.path">
            {{ item.name }}
          </router-link>
        </template>
      </div> -->
      <div className="layout-right">
        <root-page v-if="isRootPage" />
        <router-view />
      </div>
    </div>
  </div>
</template>

<style lang="scss" scoped>
.layout {
  text-align: center;
}
</style>
